name = "Jade ğŸ”"
filename = "Jade-1.16.4-2.8.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3597/364/Jade-1.16.4-2.8.1.jar"
hash-format = "sha1"
hash = "bfb8f6c0c755ed7f86eaa4851e91322272ee7b6d"

[update]
[update.curseforge]
file-id = 3597364
project-id = 324717
